version: '3'
services:
  mongodb:
    image: mongo
    container_name: bookstore-auth-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - C:\volumes-docker\bookstore-auth:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: bookstore-purchase-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Pass
    volumes:
      - C:\volumes-docker\bookstore-purchase:/var/opt/mssql/data